name: Build Chat Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            generator: "Visual Studio 17 2022"
            config: Release
          - os: ubuntu-latest
            generator: "Unix Makefiles"
            config: Release
          - os: macos-latest
            generator: "Unix Makefiles"
            config: Release

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -G "${{ matrix.generator }}" -DCMAKE_BUILD_TYPE=${{ matrix.config }}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{ matrix.config }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.os }}
        path: |
          ${{github.workspace}}/build/${{ matrix.config }}/chat_client.exe
          ${{github.workspace}}/build/chat_client
        if-no-files-found: ignore